name: Tests
on: push

jobs:
  # PHP Tests
  # ---------------------------------------------------------------
  php:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: |
            composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
            composer global require squizlabs/php_codesniffer wp-coding-standards/wpcs
      - name: PHPCS
        run: |
            phpcs --config-set show_warnings 0
            phpcs
      # - name: PHPUnit
      #   run: php -d memory_limit=-1 ./vendor/bin/phpunit
